version: '3.6'
services:
  honest:
    container_name: honest
    restart: always
    build: ..
    networks:
      - dc-net
    environment:
#      DB_NAME: honest

      #CONFIG SERVER
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: honest
      NAMESPACE: dev-dc
      M_TOKEN: ${M_TOKEN}
      #END CONFIG SERVER
    ports:
      - 86:80
networks:
  dc-net:
    external: true